timeout: 3

/Katro
    protocol: limine
    path: boot():/boot/Katro.elf

/Katro (No file system)
    comment: Use this entry if you don't want to use the file system
    cmdline: nofs
    protocol: limine
    path: boot():/boot/Katro.elf